#!/bin/bash

set -o errexit
set -o nounset

# get a version and exit.
if [ $1 = 'version' ]; then
  VERDIR=$2
  CMD=`egrep ^version: /Procfile | cut -f 2 -d ':'`
  trap `${CMD} 2> ${VERDIR}/version`
  IFS=$'\n'
  RES=`cat ${VERDIR}/version`
  for line in ${RES}; do
    if [[ ${line} =~ ^(A5-miseq version) ]]; then
        `echo ${line} > $2/version`
    fi
  done
  exit 0
fi

# Destination output directory
DIR=$4

# Set up logging
LOG=$DIR/log.txt
exec  > >(tee ${LOG})
exec 2>&1
set -o xtrace

PREFIX='assembly'

# Source reads in this container
INPUT1=$2
INPUT2=$3

# Determine which process to run
PROC=$1
CMD=$(egrep ^${PROC}: /Procfile | cut -f 2 -d ':')

if [[ -z ${CMD} ]]; then
  echo "Abort, no proc found for ${PROC}."
  exit 1
fi

cd $DIR && eval ${CMD}


# Destination scaffold or contigs file (only "contigs" produced for --metagenome)
ASSEMBLY=${DIR}/assembly.final.scaffolds.fasta
if [ ! -f $ASSEMBLY ]; then
  ASSEMBLY=${DIR}/assembly.contigs.fasta
fi
cp $ASSEMBLY $DIR/contigs.fa
chmod -R 777 $DIR/assembly.*
